### ISSUE TITLE
Cannot find the configuration file for your board!

### ISSUE THREAD

**Issue by coeus-innovations** [Ebiroll/RAK811_BreakBoard#1]
I followed your readme until
`pio run`
then I get an error

> [Tue Mar  6 00:47:21 2018] Processing rak811 (platform: ststm32; board: rak811; framework: mbed)
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: ST STM32 > Rak811
SYSTEM: STM32L151CB 32MHz 32KB RAM (125KB Flash)
Cannot find the configuration file for your board! Please read instructions here /Users/xxxxx/.platform
io/packages/framework-mbed/platformio/README.txt

**Comment by Ebiroll** [comment]
Are you sure you copied the rak811.json file to the boards directory?
It should be in
/Users/xxxxx/.platformio/platforms/ststm32/boards

**Comment by coeus-innovations** [comment]
Yes the file is at the right path. Is there anything else I need to pay attention with?

**Comment by coeus-innovations** [comment]
Sorry my bad - I have missed out the most obvious.
I have not copied the 'src', 'lib' folder as well as platformio.ini file to a project folder, and I jumped in when I saw the error.
